server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: 1224
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true

jwt:
  secret: "zOjunKVuH2JggLQVCG9RNcEl3/5SHnhAvhAjabVG/YA="
  expiration: 60000 # Expiration in milliseconds (1 day in this case)
  refresh-token:
    expiration : 600000   # 10 Days