server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: 1224
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  cache:
    type: redis
    redis:
      time-to-live: 60000
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
  data:
    redis:
      host: localhost
      port: 9999
      database: 7
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest

jwt:
  secret: "zOjunKVuH2JggLQVCG9RNcEl3/5SHnhAvhAjabVG/YA="
  expiration: 60000 # Expiration in milliseconds (1 day in this case)
  refresh-token:
    expiration : 600000   # 10 Days

